pipeline {
    agent any

    tools {
        jdk 'jdk11'
        maven 'maven3'
    }

    environment {
        SCANNER_HOME = tool 'sonar-scanner'
    }

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', changelog: false, poll: false, url: 'https://github.com/jaiswaladi246/Ekart.git'
            }
        }

        stage('Compile') {
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('Sonarqube Analysis') {
            steps {
                sh """
                    $SCANNER_HOME/bin/sonar-scanner \
                    -Dsonar.url=http://34.226.31.191:9000/ \
                    -Dsonar.login=squ_62e3dd71e71a1abf9f97b9d18f86af0574b60589 \
                    -Dsonar.projectName=shopping-cart \
                    -Dsonar.java.binaries=. \
                    -Dsonar.projectKey=shopping-cart
                """
            }
        }

        stage('OWASP SCAN') {
            steps {
                sh '/opt/dependency-check/dependency-check/bin/dependency-check.sh --project shopping-cart --scan .'
            }
        }

        stage('Build Application') {
            steps {
                sh 'mvn clean install -DskipTests'
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
                    withDockerRegistry(credentialsId: '6b3dadba-e387-4577-8ee8-af3d39b7e317') {
                        sh 'docker build -t shopping:latest -f docker/Dockerfile .'
                        sh 'docker tag shopping:latest za357627acc1/shopping:latest'
                        sh 'docker push za357627acc1/shopping:latest'
                    }
                }
            }
        }
    }

    post {
        success {
            build job: 'CD pipe P2'
        }
    }
}
